django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio_app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('posts/', views.posts, name="posts"),
    path('post/<slug:slug>', views.post, name="post"),
    path('profile/', views.profile, name="profile"),



#CRUD url patterns below
    path('create_post', views.createPost, name="create_post"),
    path('update_post/<slug:slug>', views.updatePost, name="update_post"),
    path('delete/<slug:slug>', views.deletePost, name="delete_post"),

    path('send_email/', views.sendEmail, name="send_email"),
]

portfolio_app/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    

class Post(models.Model):
    heading = models.CharField(max_length=200)
    sub_heading = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to="images", default="/images/placeholder.png")
    body = RichTextUploadingField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, null=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.heading

    def save(self, *args, **kwargs):

        if self.slug == None:

            slug = slugify(self.heading)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.heading) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()

            self.slug = slug

        super().save(*args, **kwargs)           

portfolio_app/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post

class PostForm(ModelForm):
    
    class Meta():
        model = Post
        fields = '__all__'

        widgets = {
			'tags':forms.CheckboxSelectMultiple(),
		}

portfolio_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

from .models import Post
from .forms import PostForm
from .filters import PostFilter

# Create your views here.
def home(request):
    posts = Post.objects.filter(active=True, featured=True)[0:3]

    context = {'posts': posts}
    return render(request, 'portfolio_app/index.html', context)

def posts(request):
    posts = Post.objects.filter(active=True)
    myFilter = PostFilter(request.GET, queryset=posts)
    posts = myFilter.qs

    page = request.GET.get('page')
    paginator = Paginator(posts, 3)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'myFilter': myFilter}
    return render(request, 'portfolio_app/posts.html', context)

def post(request, slug):
    post = Post.objects.get(slug=slug)
    context = {'post': post}

    return render(request, 'portfolio_app/post.html', context)

def profile(request):
    return render(request, 'portfolio_app/profile.html')


#CRUD Views Below
@login_required(login_url="home")
def createPost(request):
    form = PostForm()

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('posts')

    context = {'form': form}
    return render(request, 'portfolio_app/post_form.html', context)


@login_required(login_url="home")
def updatePost(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts')

    context = {'form': form}
    return render(request, 'portfolio_app/post_form.html', context)


@login_required(login_url="home")
def deletePost(request, slug):
    post = Post.objects.get(slug=slug)
    if request.method == 'POST':
        post.delete()
        return redirect('posts')
    context = {'item':post}
    return render(request, 'portfolio_app/delete.html', context)


def sendEmail(request):

    if request.method == 'POST':

        template = render_to_string('portfolio_app/email_template.html', {
            'name': request.POST['name'],
            'email': request.POST['email'],
            'message': request.POST['message'],
        })

        email = EmailMessage(
            request.POST['subject'],
            template,
            settings.EMAIL_HOST_USER,
            ['simeonbogg@gmail.com']

        )

        email.fail_silently = False
        email.send()

    return render(request, 'portfolio_app/email_sent.html')

portfolio_app/templates/portfolio_app/delete.html
{% extends 'portfolio_app/main.html' %}
{% load static %}
{% block content %}

<div class="main-container">
    <form method="POST" action="">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ item }}?</p>
        <input class="btn btn-danger" type="submit" value="Confirm">

    </form>
</div>

{% endblock content %}

portfolio_app/templates/portfolio_app/email_sent.html
{% extends 'portfolio_app/main.html' %}

{% block content %}

<style type="text/css">
    html, body {
        height: 100%;
    }

    #page-wrapper {
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        background-color: #eaeaea;
    }

    #success-box{
		max-width: 800px;
		height: auto;
		background-color: #fff;
		border:1px solid #888;
		border-radius: 5px;
		padding: 15px;
	}

	#success-box p{
		font-size: 18px;
	}
</style>

<div id="page-wrapper">
    <div id="success-box" class="content-block">
        <h1>Thanks for reaching out!</h1>
        <p>Your message was successfully sent. I will do my best to get back to you as soon as possible.</p>
        <a id="back-btn" class="btn btn-success" href="{% url 'home' %}">BACK TO HOME PAGE</a>
    </div>
</div>

{% endblock content %}

portfolio_app/templates/portfolio_app/email_template.html
{{name}}

{{email}}

{{message}}

portfolio_app/templates/portfolio_app/home.html
{% extends 'portfolio_app/main.html' %}

{% block content %}
<h2>Home Template</h2>
{% endblock content %}

portfolio_app/templates/portfolio_app/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Simeon Bogg</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}" >

    <link id="theme-style" rel="stylesheet" type="text/css" href="" >

</head>
<body>
    <section class="s1">
        <div class="main-container">

            <div class="greeting-wrapper">
                <h1>Hi, I'm Simeon Bogg</h1>
            </div>
            <div class="intro-wrapper">
                {% include 'portfolio_app/navbar.html' %}
                
                <div class="left-column">
                    <img id="profile_pic" src="{% static 'images/simeon_bogg2.jpg' %}">
                    <h5 style="text-align: center; line-height: 0;">Personalise Theme</h5>
                    
                    <div id="theme-options-wrapper">
                        <div data-mode="light" id="light-mode" class="theme-dot"></div>
                        <div data-mode="blue" id="blue-mode" class="theme-dot"></div>
                        <div data-mode="green" id="green-mode" class="theme-dot"></div>
                        <div data-mode="purple" id="purple-mode" class="theme-dot"></div>
                    </div>
                    <p id="settings-note">*Theme settings will be saved for<br>your next visit</p>
                </div>

                <div class="right-column">
                    <div id="preview-shadow">
                        <div id="preview">
                            <div id="corner-tl" class="corner"></div>
                            <div id="corner-tr" class="corner"></div>
                        
                            <h3>What I Do</h3>
                            <p>I am a backend developer from the UK,
                                looking for my first professional role as a django developer.</p>

                            <div id="corner-bl" class="corner"></div>
                            <div id="corner-br" class="corner"></div>    
                        </div>
                    </div>
                </div>
            </div>
    </div>
        </div>
    </section>

    <section class="s2">
        <div class="main-container">

            <div class="about-wrapper">

                <div class="about-me">
                    <h4>About Me</h4>
                    <p>I build new projects to learn more about the Django framework</p>
                   
                    <p>My aim is to get a job as a backend developer.</p>
                

                    <hr>

                    <h4>TOP EXPERTISE</h4>

                    <p>Backend developer with focus on the Django. <a target="_blank" href="my_cv_2024.pdf">Download CV</a></p> <!--Add CV to static folder and link to it {% static 'filename' %}-->

                    <div id="skills">
                        <ul>
                            <li>Python</li>
                            <li>Django</li>   
                        </ul>

                        <ul>
                            <li>SQL (Postgres, Oracle)</li>
                            <li>HTML/CSS</li>
                        </ul>
                    </div>
                </div>

                <div class="social-links">
                    <h3>Find me on GitHub and LinkedIn:</h3>
                    <img id="social-image" src="{% static 'images/work_socials.png' %}">
                    <a target="_blank" href="#">GitHub: SimeonBogg</a>
                    <br>
                    <a target="_blank" href="#">LinkedIn: Simeon Bogg</a>
                </div>

            </div>

        </div>
    </section>

    <section class="s1">
        <div class="main-container">

            <h3 style="text-align: center;">Some of my past projects</h3>

            <div class="post-wrapper">
                {% for post in posts %}
                <div>
                    <div class="post">
                        <img class="thumbnail" src="{{ post.thumbnail.url }}">
                        <div class="post-preview">
                            <h6 class="post-title">{{post.heading}}</h6>
                            <p class="post-intro">{{post.sub_heading}}</p>
                            <a href="{% url 'post' post.slug %}">Read More</a>
                            <hr>
                                {% for tag in post.tags.all %}
                                    <span class="tag">{{tag}}</span>
                                {% endfor %}
                            <hr>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <p style="text-align: center">
                <a href="{% url 'posts' %}">View More</a>    
            </p>
        </div>
    </section>

    <section class="s2">
        <div class="main-container">
            <h3 style="text-align: center;">Get In Touch</h3>

            <form id="contact-form" method="POST" action="{% url 'send_email' %}">
                {% csrf_token %}
                <label>Name</label>
                <input class="input-field" type="text" name="name">

                <label>Subject</label>
                <input class="input-field" type="text" name="subject">

                <label>Email</label>
                <input class="input-field" type="text" name="email">

                <label>Message</label>
                <textarea class="input-field" type="text" name="message"></textarea>

                <input id="submit-btn" type="submit" value="Send">
            </form>
        </div>
    </section>

    <script type="text/javascript">
        let static = "{% static 'css' %}"
    </script>

    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>

</body>
</html>

portfolio_app/templates/portfolio_app/main.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Simeon Bogg</title>

        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
    
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">
    
        <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}" >

    </head>
    <body>
        {% include 'portfolio_app/navbar.html' %}
        
        {% block content %}
        <!--content goes here-->
        {% endblock content %}
    </body>
</html>

portfolio_app/templates/portfolio_app/navbar.html
<div class="nav-wrapper">
    <a href="{% url 'home' %}">
        <div class="dots-wrapper">
            <div id="dot-1" class="browser-dot"></div>
            <div id="dot-2" class="browser-dot"></div>
            <div id="dot-3" class="browser-dot"></div>
        </div>
    </a>
    <ul id="navigation">
    <li><a href="{% url 'home' %}">Contact</a></li>
    {% if request.user.is_authenticated %}
        <li><a href="{% url 'create_post' %}">Create Post</a></li>
    {% endif %}
    </ul>
</div>

portfolio_app/templates/portfolio_app/post.html
{% extends 'portfolio_app/main.html' %}
{% load static %}
{% block content %}
<div class="main-container">
    <img src="{{post.thumbnail.url}}">
    <h1>{{post.heading}}</h1>

    <h4>{{post.sub_heading}}</h4>
    
    <p>{{post.body|safe}}</p>
</div>
{% endblock content %}

portfolio_app/templates/portfolio_app/post_form.html
{% extends 'portfolio_app/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
    #div_id_tags > div{
        max-height: 100px;
        overflow-y: scroll;
        border: 1px solid #888;
        padding: 5px;
        border-radius: 5px;
    }

    .form-group {
        margin-bottom: 10px;
    }

    #search-button {
        padding-bottom: 15px;
    }


</style>

<div class="main-container">
        <h3>Post Form</h3>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <div id="search-button">
                <input style="background-color: #0275d8; color: #fff" type="submit" value="Submit Post">
            </div>
        </form>
</div>

{% endblock content %}

portfolio_app/templates/portfolio_app/posts.html
{% extends 'portfolio_app/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
	#div_id_tags, #id_tags {
		overflow-y: scroll;
		max-height: 100px;
		padding: 5px;
	}

    .form-group {
        padding-bottom: 15px;
    }

    #search-button {
        padding-top: 15px;
    }


    .post-wrapper {
        padding-top: 30px;
    }

    .pagination {
        display: flex;
        list-style: none;
        padding: 0;
        margin: 20px 0;  /* Adjust the margin as needed */
    }

    .page-item {
        margin-right: 5px;  /* Adjust the margin as needed */
    }

    .page-link {
        color: #fff;
        background-color: #0275d8;
        border: 1px solid #0275d8;
        padding: 6px 12px;  /* Adjust the padding as needed */
        text-decoration: none;
    }

    .page-link:hover,
    .page-link:focus {
        background-color: #01447e;
        border-color: #01447e;
    }

    .active .page-link {
        background-color: #01447e;
        border-color: #01447e;
    }

</style>

<div class="main-container">
    <h1 style="text-align: center;">Posts</h1>

    <form id="searchForm" method="GET">
        {{myFilter.form|crispy}}
        <div id="search-button">
            <input id="button" style="background-color: #0275d8; color: #fff" type="submit" value="search">
        </div>
    </form>
    
    <div class="post-wrapper">
        {% for post in posts %}
        <div>
            <div class="post">
                <img class="thumbnail" src="{{ post.thumbnail.url }}">
                <div class="post-preview">
                    <h6 class="post-title">{{post.heading}}</h6>
                    <p class="post-intro">{{post.sub_heading}}</p>
                    <a href="{% url 'post' post.slug %}">Read More </a>
                    {% if request.user.is_authenticated %}
                     | <a href="{% url 'update_post' post.slug %}">Edit</a>
                     | <a href="{% url 'delete_post' post.slug %}">Delete</a>
                    {% endif %}
                    <hr>
                    {% for tag in post.tags.all %}
                        <span class="tag">{{tag}}</span>
                    {% endfor %}
                    <hr>

                </div>
            </div>
        </div>
        {% empty %}
            <h3>No posts found...</h3>
        {% endfor %}
    </div>

    <div class="row">
        {% if posts.has_other_pages %}

        <ul class="pagination">
            {% if posts.has_previous %}
					<li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">&laquo</a></li>

					<li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
			{% endif %}

            {% for i in posts.paginator.page_range %}
                {% if posts.number == i %}
                    <li class="page-item"><a class="active page-link">{{i}}</a></li>
                {% else %}
                    <li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
                {% endif %}
            {% endfor %}

            {% if posts.has_next %}
					<li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>

					<li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo</a></li>
			{% endif %}
        </ul>

        {% endif %}
    </div>

    <script tpye="text/javascript">
        let searchForm = document.getElementById('searchForm')
        let pageLinks = document.getElementsByClassName('page-link')

        for(var i=0; pageLinks.length > i; i++){
            pageLinks[i].addEventListener('click', function(e){
                e.preventDefault()
                let page = this.dataset.page
                console.log('Page:', page)
                searchForm.innerHTML += `<input value="${page}" name="page" hidden>`
                searchForm.submit()
            })
        }
    </script>

</div>
{% endblock content %}

portfolio_app/templates/portfolio_app/profile.html
{% extends 'portfolio_app/main.html' %}

{% block content %}
<h2>Profile Template</h2>
{% endblock content %}